project:
  type: website
  output-dir: docs 

website:
  title: "Yohann's blog"
  repo-url: github.com/ymansiaux/yohann-data
  search: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/yohann-mansiaux-1816aa20/
format:
  html:
    theme: cosmo
    css: styles.css



