project:
  type: website
  output-dir: docs 

website:  
  title: "Yohann's blog"
  description: "Yohann Mansiaux's blog - R, dev and other stuff"
  repo-url: github.com/ymansiaux/yohann-data
  site-url: "https://ymansiaux.github.io/yohann-data/"
  google-analytics: "G-YYG34HFXPT"
  cookie-consent: true
  search: true
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About me"
        href: about.qmd
      - text: "r-bloggers" 
        href: https://www.r-bloggers.com/
    right:      
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/yohann-mansiaux-1816aa20/
      - text: Bluesky
        href: https://bsky.app/profile/yosky.bsky.social
      - icon: envelope
        text: email
        url: "mailto:yohann.mansiaux@gmail.com"      

format:
  html:
    theme: cosmo
    css: styles.css



